### ISSUE TITLE
Animation Bug

### ISSUE THREAD

**Issue by olivierek6** [Zaseth/KITSUNE-MODIFIED#5]
Any idea why this happens?
https://cdn.discordapp.com/attachments/290160473020563456/368821304440127489/Screenshot_531.png

**Comment by Zaseth** [comment]
That's not Kitsune's fault. Basically, your penguins.swf (play/v2/content/global/penguin/penguin.swf) seems to be AS3. CP takes the sprite IDS from the penguin.swf file and sends them as a packet to do your sprite. It seems like the ninja sprite is the same sprite as the drilling. You can still see the helmet because that's the item itself. Here is the one i've been using for CPLite: https://mega.nz/#!hoRHGIRT!BiC-XIWZc53pna31RNtmUj_yDNu5ChAQklapDS1yEm4
